version: '2'

services:
  db:
    image: 'postgres:16.0-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=database
    ports:
      - 5432:5432