spring:
  application:
    name: context-demo
  config:
    import: file:./dev.yml
  datasource:
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: false

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env