spring:
  cloud:
    refresh:
      never-refreshable:
  application:
    name: context-demo
  config:
    import: file:./dev.yml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: false

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env